listOf(
    Extension(
        name = "MtlNovelEn",
        versionCode = 2,
        libVersion = "2",
        lang = "en",
        description = "",
        nsfw = false,
        icon = DEFAULT_ICON,
        assetsDir = "multisrc/mtlnovel/mtlnovelen/assets",
        sourceDir = "mtlnovelen",
    ),
    Extension(
        name = "MtlNovelFr",
        versionCode = 2,
        libVersion = "2",
        lang = "fr",
        description = "",
        nsfw = false,
        icon = DEFAULT_ICON,
        assetsDir = "multisrc/mtlnovel/mtlnovelen/assets",
        sourceDir = "mtlnovelfr",
    ),
    Extension(
        name = "MtlNovelEs",
        versionCode = 2,
        libVersion = "2",
        lang = "es",
        description = "",
        nsfw = false,
        icon = DEFAULT_ICON,
        assetsDir = "multisrc/mtlnovel/mtlnovelen/assets",
        sourceDir = "mtlnoveles",
    ),
    Extension(
        name = "MtlNovelIn",
        versionCode = 2,
        libVersion = "2",
        lang = "in",
        description = "",
        nsfw = false,
        icon = DEFAULT_ICON,
        assetsDir = "multisrc/mtlnovel/mtlnovelen/assets",
        sourceDir = "mtlnovelin",
    ),
).also(::register)
