name: New Extension Request
description: Request a new source extension
title: "[Extension Request] "
labels: ["extension-request"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for requesting a new extension!
        
  - type: input
    id: source-name
    attributes:
      label: Source Name
      description: What is the name of the website?
      placeholder: e.g., NovelExample
    validations:
      required: true
      
  - type: input
    id: source-url
    attributes:
      label: Source URL
      description: What is the URL of the website?
      placeholder: https://example.com
    validations:
      required: true
      
  - type: dropdown
    id: language
    attributes:
      label: Language
      description: What language is the source in?
      options:
        - English
        - Arabic
        - Chinese
        - French
        - Indonesian
        - Turkish
        - Other
    validations:
      required: true
      
  - type: input
    id: language-other
    attributes:
      label: Other Language
      description: If you selected "Other", please specify
      
  - type: dropdown
    id: nsfw
    attributes:
      label: NSFW Content
      description: Does this source contain NSFW content?
      options:
        - "No"
        - "Yes"
    validations:
      required: true
      
  - type: textarea
    id: additional
    attributes:
      label: Additional Information
      description: Any additional information about the source (e.g., requires login, has cloudflare protection, etc.)
