listOf(
    Extension(
        name = "Readwn",
        versionCode = 1,
        libVersion = "1",
        lang = "en",
        description = "",
        nsfw = false,
        icon = DEFAULT_ICON,
        assetsDir = "multisrc/madara/readwn/assets",
        sourceDir = "readwn",
    ),
    Extension(
        name = "Novelmt",
        versionCode = 1,
        libVersion = "1",
        lang = "en",
        description = "",
        nsfw = false,
        icon = DEFAULT_ICON,
        assetsDir = "multisrc/madara/novelmt/assets",
        sourceDir = "novelmt",
    ),
    Extension(
        name = "Ltnovel",
        versionCode = 1,
        libVersion = "1",
        lang = "en",
        description = "",
        nsfw = false,
        icon = DEFAULT_ICON,
        assetsDir = "multisrc/madara/ltnovel/assets",
        sourceDir = "ltnovel",
    ),
).also(::register)