listOf(
    Extension(
        name = "Readwn",
        versionCode = 2,
        libVersion = "2",
        lang = "en",
        description = "",
        nsfw = false,
        icon = DEFAULT_ICON,
        assetsDir = "multisrc/readwn/readwn/assets",
        sourceDir = "readwn",
    ),
    Extension(
        name = "Novelmt",
        versionCode = 2,
        libVersion = "2",
        lang = "en",
        description = "",
        nsfw = false,
        icon = DEFAULT_ICON,
        assetsDir = "multisrc/readwn/novelmt/assets",
        sourceDir = "novelmt",
    ),
    Extension(
        name = "Ltnovel",
        versionCode = 2,
        libVersion = "2",
        lang = "en",
        description = "",
        nsfw = false,
        icon = DEFAULT_ICON,
        assetsDir = "multisrc/readwn/ltnovel/assets",
        sourceDir = "ltnovel",
    ),
    Extension(
        name = "Wuxiabox",
        versionCode = 1,
        libVersion = "2",
        lang = "en",
        description = "",
        nsfw = false,
        icon = DEFAULT_ICON,
        assetsDir = "multisrc/readwn/wuxiabox/assets",
        sourceDir = "wuxiabox",
    ),
    Extension(
        name = "Wuxiafox",
        versionCode = 1,
        libVersion = "2",
        lang = "en",
        description = "",
        nsfw = false,
        icon = DEFAULT_ICON,
        assetsDir = "multisrc/readwn/wuxiafox/assets",
        sourceDir = "wuxiafox",
    ),
    Extension(
        name = "FanMTL",
        versionCode = 1,
        libVersion = "2",
        lang = "en",
        description = "",
        nsfw = false,
        icon = DEFAULT_ICON,
        assetsDir = "multisrc/readwn/fanmtl/assets",
        sourceDir = "fanmtl",
    ),
    Extension(
        name = "WuxiaSpot",
        versionCode = 1,
        libVersion = "2",
        lang = "en",
        description = "",
        nsfw = false,
        icon = DEFAULT_ICON,
        assetsDir = "multisrc/readwn/wuxiaspot/assets",
        sourceDir = "wuxiaspot",
    ),
    Extension(
        name = "WuxiaV",
        versionCode = 1,
        libVersion = "2",
        lang = "en",
        description = "",
        nsfw = false,
        icon = DEFAULT_ICON,
        assetsDir = "multisrc/readwn/wuxiav/assets",
        sourceDir = "wuxiav",
    ),
).also(::register)
