package tachiyomix.compiler

import com.google.devtools.ksp.processing.CodeGenerator
import com.google.devtools.ksp.processing.Dependencies
import com.google.devtools.ksp.processing.KSPLogger
import com.google.devtools.ksp.processing.Resolver
import com.google.devtools.ksp.processing.SymbolProcessor
import com.google.devtools.ksp.processing.SymbolProcessorEnvironment
import com.google.devtools.ksp.processing.SymbolProcessorProvider
import com.google.devtools.ksp.symbol.KSAnnotated
import com.google.devtools.ksp.symbol.KSClassDeclaration
import com.google.devtools.ksp.validate
import com.squareup.kotlinpoet.ClassName
import com.squareup.kotlinpoet.FileSpec
import com.squareup.kotlinpoet.FunSpec
import com.squareup.kotlinpoet.KModifier
import com.squareup.kotlinpoet.PropertySpec
import com.squareup.kotlinpoet.TypeSpec
import com.squareup.kotlinpoet.ksp.writeTo

/**
 * KSP Processor for generating theme-based source extensions.
 * 
 * Processes @MadaraSource and @ThemeSource annotations to generate
 * source classes that extend theme base classes.
 */
class ThemeSourceProcessor(
    private val codeGenerator: CodeGenerator,
    private val logger: KSPLogger,
    private val options: Map<String, String>
) : SymbolProcessor {

    override fun process(resolver: Resolver): List<KSAnnotated> {
        // Process @MadaraSource annotations
        val madaraSources = resolver.getSymbolsWithAnnotation(MADARA_SOURCE_ANNOTATION)
            .filterIsInstance<KSClassDeclaration>()
            .filter { it.validate() }
            .toList()

        madaraSources.forEach { generateMadaraSource(it) }

        // Process @ThemeSource annotations
        val themeSources = resolver.getSymbolsWithAnnotation(THEME_SOURCE_ANNOTATION)
            .filterIsInstance<KSClassDeclaration>()
            .filter { it.validate() }
            .toList()

        themeSources.forEach { generateThemeSource(it) }

        return emptyList()
    }

    private fun generateMadaraSource(config: KSClassDeclaration) {
        val annotation = config.annotations.first { 
            it.shortName.asString() == "MadaraSource" 
        }
        
        val args = annotation.arguments.associate { 
            it.name?.asString() to it.value 
        }
        
        val name = args["name"] as String
        val baseUrl = args["baseUrl"] as String
        val lang = args["lang"] as String
        val id = args["id"] as Long
        val novelsPath = args["novelsPath"] as? String ?: "novel"
        val novelPath = args["novelPath"] as? String ?: "novel"
        val chapterPath = args["chapterPath"] as? String ?: "novel"
        
        val packageName = config.packageName.asString()
        val className = "${name}Generated"
        
        val madaraClass = ClassName("ireader.madara", "Madara")
        val pathClass = ClassName("ireader.madara", "Path")
        val depsClass = ClassName("ireader.core.source", "Dependencies")
        val extensionAnnotation = ClassName("tachiyomix.annotations", "Extension")
        
        val classSpec = TypeSpec.classBuilder(className)
            .addAnnotation(extensionAnnotation)
            .addModifiers(KModifier.ABSTRACT)
            .primaryConstructor(
                FunSpec.constructorBuilder()
                    .addParameter("deps", depsClass)
                    .build()
            )
            .superclass(madaraClass)
            .addSuperclassConstructorParameter("deps")
            .addSuperclassConstructorParameter("%L", id)
            .addSuperclassConstructorParameter("%S", baseUrl)
            .addSuperclassConstructorParameter("%S", name)
            .addSuperclassConstructorParameter("%S", lang)
            .addSuperclassConstructorParameter(
                "%T(%S, %S, %S)", 
                pathClass, novelsPath, novelPath, chapterPath
            )
            .build()
        
        FileSpec.builder(packageName, className)
            .addType(classSpec)
            .addFileComment("Generated by ThemeSourceProcessor - DO NOT EDIT")
            .build()
            .writeTo(codeGenerator, Dependencies(false, config.containingFile!!))
        
        logger.info("Generated Madara source: $packageName.$className")
    }

    private fun generateThemeSource(config: KSClassDeclaration) {
        val annotation = config.annotations.first { 
            it.shortName.asString() == "ThemeSource" 
        }
        
        val args = annotation.arguments.associate { 
            it.name?.asString() to it.value 
        }
        
        val name = args["name"] as String
        val baseUrl = args["baseUrl"] as String
        val lang = args["lang"] as String
        val id = args["id"] as Long
        val theme = args["theme"] as String
        
        val packageName = config.packageName.asString()
        val className = "${name}Generated"
        
        // Parse theme class name
        val themePackage = theme.substringBeforeLast(".")
        val themeClass = theme.substringAfterLast(".")
        val themeClassName = ClassName(themePackage, themeClass)
        
        val depsClass = ClassName("ireader.core.source", "Dependencies")
        val extensionAnnotation = ClassName("tachiyomix.annotations", "Extension")
        
        val classSpec = TypeSpec.classBuilder(className)
            .addAnnotation(extensionAnnotation)
            .addModifiers(KModifier.ABSTRACT)
            .primaryConstructor(
                FunSpec.constructorBuilder()
                    .addParameter("deps", depsClass)
                    .build()
            )
            .superclass(themeClassName)
            .addSuperclassConstructorParameter("deps")
            .addSuperclassConstructorParameter("%L", id)
            .addSuperclassConstructorParameter("%S", baseUrl)
            .addSuperclassConstructorParameter("%S", name)
            .addSuperclassConstructorParameter("%S", lang)
            .addProperty(
                PropertySpec.builder("id", Long::class, KModifier.OVERRIDE)
                    .initializer("%L", id)
                    .build()
            )
            .addProperty(
                PropertySpec.builder("name", String::class, KModifier.OVERRIDE)
                    .initializer("%S", name)
                    .build()
            )
            .addProperty(
                PropertySpec.builder("lang", String::class, KModifier.OVERRIDE)
                    .initializer("%S", lang)
                    .build()
            )
            .addProperty(
                PropertySpec.builder("baseUrl", String::class, KModifier.OVERRIDE)
                    .initializer("%S", baseUrl)
                    .build()
            )
            .build()
        
        FileSpec.builder(packageName, className)
            .addType(classSpec)
            .addFileComment("Generated by ThemeSourceProcessor - DO NOT EDIT")
            .build()
            .writeTo(codeGenerator, Dependencies(false, config.containingFile!!))
        
        logger.info("Generated theme source: $packageName.$className")
    }

    companion object {
        const val MADARA_SOURCE_ANNOTATION = "tachiyomix.annotations.MadaraSource"
        const val THEME_SOURCE_ANNOTATION = "tachiyomix.annotations.ThemeSource"
    }
}

class ThemeSourceProcessorProvider : SymbolProcessorProvider {
    override fun create(environment: SymbolProcessorEnvironment): SymbolProcessor {
        return ThemeSourceProcessor(
            environment.codeGenerator,
            environment.logger,
            environment.options
        )
    }
}
