import com.android.build.gradle.internal.api.ApplicationVariantImpl
import com.android.build.gradle.internal.api.BaseVariantImpl
import com.android.build.gradle.internal.api.BaseVariantOutputImpl
import com.android.builder.model.ProductFlavor

/**
 * Extension Setup Plugin
 * 
 * Configures sources to build:
 * - APK (Android)
 * - JAR (JVM/Desktop)
 * - JS init files (iOS) - generated by KSP JsExtensionProcessor
 */

plugins {
    id("com.android.application")
    kotlin("android")
    kotlin("plugin.serialization")
    id("com.google.devtools.ksp")
}

val extensionList: List<Extension> by extra

android {
    namespace = "ireader.extension"
    compileSdk = Config.compileSdk
    defaultConfig {
        minSdk = Config.minSdk
        targetSdk = Config.targetSdk
        multiDexEnabled = false
    }
    sourceSets {
        named("main") {
            manifest.srcFile("$rootDir/extensions/AndroidManifest.xml")
            java.srcDirs("main/src")
            res.srcDirs("main/res")
            resources.setSrcDirs(emptyList<Any>())
        }
        extensionList.forEach { extension ->
            val sourceDir = extension.sourceDir
            create(extension.flavor) {
                java.srcDirs("${sourceDir}/src")
                if (!extension.icon.isAssetType()) {
                    res.srcDirs("${sourceDir}/res")
                }
            }
        }
    }
    flavorDimensions.add("default")
    productFlavors {
        extensionList.forEach { extension ->
            create(extension.flavor) {
                dimension = "default"
                versionCode = extension.versionCode
                versionName = extension.versionName
                manifestPlaceholders.putAll(
                    mapOf(
                        "appName" to "IReader: ${extension.name} (${extension.lang})",
                        "sourceId" to ":${extension.sourceId}",
                        "sourceName" to extension.name,
                        "sourceLang" to extension.lang,
                        "sourceDescription" to extension.description,
                        "sourceNsfw" to if (extension.nsfw) 1 else 0,
                        "sourceIcon" to if (extension.icon == DEFAULT_ICON)
                            createExtensionIconLink(extension) else extension.icon,
                        "sourceDir" to extension.sourceDir,
                        "assetsDir" to extension.assetsDir
                    )
                )
            }
        }
    }
    lint {
        abortOnError = false
    }
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_21
        targetCompatibility = JavaVersion.VERSION_21
    }
    java {
        toolchain {
            languageVersion.set(JavaLanguageVersion.of(21))
        }
    }
    applicationVariants.all {
        this as ApplicationVariantImpl
        val extension = currentExtension() ?: return@all
        outputs.all {
            this as BaseVariantOutputImpl
            val nameLower = extension.name.lowercase()
            outputFileName = "ireader-${extension.lang}-${nameLower}-v${extension.versionName}.apk"
            processManifestForExtension(extension)
        }
    }
    dependenciesInfo {
        includeInApk = false
    }

    if (System.getenv("STORE_PATH") != null) {
        signingConfigs {
            create("release") {
                storeFile = file(System.getenv("STORE_PATH"))
                keyAlias = System.getenv("STORE_ALIAS")
                storePassword = System.getenv("STORE_PASS")
                keyPassword = System.getenv("KEY_PASS")
            }
        }
        buildTypes.all {
            signingConfig = signingConfigs.getByName("release")
        }
    }
}

tasks.register("deploy", DeployTask::class.java)


// Generate JAR for each extension (for Desktop/JVM use)
tasks.register<Jar>("extensionJar") {
    group = "build"
    description = "Create JAR containing all extension classes"
    
    archiveBaseName.set("${project.name}-extensions")
    archiveVersion.set("1.0.0")
    
    from(android.sourceSets.getByName("main").java.srcDirs)
    extensionList.forEach { extension ->
        from(android.sourceSets.getByName(extension.flavor).java.srcDirs)
    }
    
    manifest {
        attributes(
            "Implementation-Title" to project.name,
            "Implementation-Version" to "1.0.0"
        )
    }
}

tasks.findByName("repo")?.finalizedBy("extensionJar")

// Dependencies
dependencies {
    implementation(project(":defaultRes"))

    val libs = project.extensions.getByType<VersionCatalogsExtension>().named("libs")

    // Core dependencies (KMP-compatible)
    compileOnly(libs.findLibrary("ireader-core").get())
    compileOnly(libs.findLibrary("stdlib").get())
    compileOnly(libs.findLibrary("ksoup").get())
    compileOnly(libs.findLibrary("kotlinx-datetime").get())
    compileOnly(libs.findLibrary("ktor-core").get())
    compileOnly(libs.findLibrary("ktor-contentNegotiation").get())
    compileOnly(libs.findLibrary("ktor-serialization").get())
    compileOnly(libs.findLibrary("ktor-cio").get())
    compileOnly(libs.findLibrary("ktor-android").get())
    compileOnly(libs.findLibrary("ktor-okhttp").get())

    compileOnly(project(":annotations"))
    compileOnly(project(":multisrc"))
    compileOnly(project(":common"))
    ksp(project(":compiler"))

    extensionList.forEach { extension ->
        if (extension.deepLinks.isNotEmpty()) {
            add("${extension.flavor}Implementation", project(":deeplink"))
        }
        extension.projectDependencies.forEach { dependency ->
            add("${extension.flavor}Implementation", project(dependency))
        }
        extension.remoteDependencies.forEach { dependency ->
            add("${extension.flavor}Implementation", dependency)
        }
    }
}

// KSP Configuration
ksp {
    extensionList.forEach { extension ->
        val prefix = extension.flavor
        arg("${prefix}_name", extension.name)
        arg("${prefix}_lang", extension.lang)
        arg("${prefix}_id", extension.sourceId.toString())
        arg("${prefix}_has_deeplinks", extension.deepLinks.isNotEmpty().toString())
        arg("${prefix}_enable_js", extension.enableJs.toString())
    }
}

fun BaseVariantImpl.currentExtension(): Extension? {
    val flavor = (productFlavors as List<ProductFlavor>).first()
    return extensionList.firstOrNull { it.flavor == flavor.name }
}


// ============================================================================
// JS Build Support (for iOS)
// ============================================================================

// Store JS-enabled extensions for configuration cache compatibility
val jsEnabledExtensions = extensionList.filter { it.enableJs }
val hasJsExtensions = jsEnabledExtensions.isNotEmpty()

/**
 * Task to collect KSP-generated JS init files to a central location.
 */
if (hasJsExtensions) {
    tasks.register<Copy>("collectJsInitFiles") {
        group = "js"
        description = "Collect KSP-generated JS init files for iOS build"
        
        jsEnabledExtensions.forEach { extension ->
            from("build/generated/ksp/${extension.flavor}Release/kotlin") {
                include("**/js/*.kt")
            }
        }
        
        into(layout.buildDirectory.dir("js-sources"))
    }

    /**
     * Task to generate index.json for JS sources.
     */
    tasks.register("generateJsSourceIndex") {
        group = "js"
        description = "Generate index.json for JS sources"
        
        val outputDir = layout.buildDirectory.dir("js-dist")
        outputs.dir(outputDir)
        
        doLast {
            val indexFile = outputDir.get().file("index.json").asFile
            indexFile.parentFile.mkdirs()
            
            val sources = jsEnabledExtensions.joinToString(",\n") { ext ->
                """    {
      "id": "${ext.sourceId}",
      "name": "${ext.name}",
      "lang": "${ext.lang}",
      "version": "${ext.versionName}",
      "file": "${ext.name.lowercase().replace(" ", "-")}.js",
      "nsfw": ${ext.nsfw}
    }"""
            }
            
            indexFile.writeText("""{
  "version": 1,
  "sources": [
$sources
  ]
}""")
            
            logger.lifecycle("Generated JS source index at ${indexFile.absolutePath}")
        }
    }
}
