listOf(
    Extension(
        name = "Neosekaitranslations",
        versionCode = 1,
        libVersion = "1",
        lang = "en",
        description = "",
        nsfw = false,
        icon = DEFAULT_ICON,
        assetsDir = "multisrc/madara/neosekaitranslations/assets",
        sourceDir = "neosekaitranslations",
    ),
    Extension(
        name = "Armtl",
        versionCode = 1,
        libVersion = "1",
        lang = "ar",
        description = "",
        nsfw = false,
        icon = DEFAULT_ICON,
        assetsDir = "multisrc/madara/armtl/assets",
        sourceDir = "armtl",
    ),
    Extension(
        name = "Zinnovel",
        versionCode = 1,
        libVersion = "1",
        lang = "en",
        description = "",
        nsfw = false,
        icon = DEFAULT_ICON,
        assetsDir = "multisrc/madara/zinnovel/assets",
        sourceDir = "zinnovel",
    ),
    Extension(
        name = "NovelTranslate",
        versionCode = 1,
        libVersion = "1",
        lang = "en",
        description = "",
        nsfw = false,
        icon = DEFAULT_ICON,
        assetsDir = "multisrc/madara/noveltranslate/assets",
        sourceDir = "noveltranslate",
    ),
).also(::register)