listOf(
    Extension(
        name = "Neosekaitranslations",
        versionCode = 1,
        libVersion = "1",
        lang = "en",
        description = "",
        nsfw = false,
        icon = DEFAULT_ICON,
        assetsDir = "multisrc/madara/neosekaitranslations/assets",
        sourceDir = "neosekaitranslations",
    ),
    Extension(
        name = "Armtl",
        versionCode = 1,
        libVersion = "1",
        lang = "ar",
        description = "",
        nsfw = false,
        icon = DEFAULT_ICON,
        assetsDir = "multisrc/madara/armtl/assets",
        sourceDir = "armtl",
    ),
    Extension(
        name = "Zinnovel",
        versionCode = 1,
        libVersion = "1",
        lang = "en",
        description = "",
        nsfw = false,
        icon = DEFAULT_ICON,
        assetsDir = "multisrc/madara/zinnovel/assets",
        sourceDir = "zinnovel",
    ),
    Extension(
        name = "NovelTranslate",
        versionCode = 1,
        libVersion = "1",
        lang = "en",
        description = "",
        nsfw = false,
        icon = DEFAULT_ICON,
        assetsDir = "multisrc/madara/noveltranslate/assets",
        sourceDir = "noveltranslate",
    ),
    Extension(
        name = "LunarLetters",
        versionCode = 1,
        libVersion = "1",
        lang = "en",
        description = "",
        nsfw = false,
        icon = DEFAULT_ICON,
        assetsDir = "multisrc/madara/lunarletters/assets",
        sourceDir = "lunarletters",
    ),
    Extension(
        name = "SleepyTranslations",
        versionCode = 1,
        libVersion = "1",
        lang = "en",
        description = "",
        nsfw = false,
        icon = DEFAULT_ICON,
        assetsDir = "multisrc/madara/sleepytranslations/assets",
        sourceDir = "sleepytranslations",
    ),
    Extension(
        name = "Freenovel",
        versionCode = 1,
        libVersion = "1",
        lang = "en",
        description = "",
        nsfw = false,
        icon = DEFAULT_ICON,
        assetsDir = "multisrc/madara/freenovel/assets",
        sourceDir = "freenovel",
    ),
    Extension(
        name = "FirstKissNovel",
        versionCode = 1,
        libVersion = "1",
        lang = "en",
        description = "",
        nsfw = false,
        icon = DEFAULT_ICON,
        assetsDir = "multisrc/madara/firstkissnovel/assets",
        sourceDir = "firstkissnovel",
    ),
    Extension(
        name = "DaoNovel",
        versionCode = 1,
        libVersion = "1",
        lang = "en",
        description = "",
        nsfw = false,
        icon = DEFAULT_ICON,
        assetsDir = "multisrc/madara/daonovel/assets",
        sourceDir = "daonovel",
    ),
    Extension(
        name = "MostNovel",
        versionCode = 1,
        libVersion = "1",
        lang = "en",
        description = "",
        nsfw = false,
        icon = DEFAULT_ICON,
        assetsDir = "multisrc/madara/mostnovel/assets",
        sourceDir = "mostnovel",
    ),
    Extension(
        name = "NovelMultiverse",
        versionCode = 1,
        libVersion = "1",
        lang = "en",
        description = "",
        nsfw = false,
        icon = DEFAULT_ICON,
        assetsDir = "multisrc/madara/novelmultiverse/assets",
        sourceDir = "novelmultiverse",
    ),
    Extension(
        name = "LightNovelHeaven",
        versionCode = 1,
        libVersion = "1",
        lang = "en",
        description = "",
        nsfw = false,
        icon = DEFAULT_ICON,
        assetsDir = "multisrc/madara/lightnovelheaven/assets",
        sourceDir = "lightnovelheaven",
    ),
    Extension(
        name = "ArNovel",
        versionCode = 1,
        libVersion = "1",
        lang = "ar",
        description = "",
        nsfw = false,
        icon = DEFAULT_ICON,
        assetsDir = "multisrc/madara/arnovel/assets",
        sourceDir = "arnovel",
    ),
    Extension(
        name = "MeioNovel",
        versionCode = 1,
        libVersion = "1",
        lang = "in",
        description = "",
        nsfw = false,
        icon = DEFAULT_ICON,
        assetsDir = "multisrc/madara/meionovel/assets",
        sourceDir = "meionovel",
    ),
    Extension(
        name = "WebNovelLover",
        versionCode = 1,
        libVersion = "1",
        lang = "en",
        description = "",
        nsfw = false,
        icon = DEFAULT_ICON,
        assetsDir = "multisrc/madara/webnovelover/assets",
        sourceDir = "webnovelover",
    ),
    Extension(
        name = "CrateNovel",
        versionCode = 1,
        libVersion = "1",
        lang = "en",
        description = "",
        nsfw = false,
        icon = DEFAULT_ICON,
        assetsDir = "multisrc/madara/cratenovel/assets",
        sourceDir = "cratenovel",
    ),
    Extension(
        name = "ClickNovel",
        versionCode = 1,
        libVersion = "1",
        lang = "en",
        description = "",
        nsfw = false,
        icon = DEFAULT_ICON,
        assetsDir = "multisrc/madara/clicknovel/assets",
        sourceDir = "clicknovel",
    ),
    Extension(
        name = "ReadWebNovels",
        versionCode = 1,
        libVersion = "1",
        lang = "en",
        description = "",
        nsfw = false,
        icon = DEFAULT_ICON,
        assetsDir = "multisrc/madara/readwebnovels/assets",
        sourceDir = "readwebnovels",
    ),
    Extension(
        name = "WBNovel",
        versionCode = 1,
        libVersion = "1",
        lang = "in",
        description = "",
        nsfw = false,
        icon = DEFAULT_ICON,
        assetsDir = "multisrc/madara/wbnovel/assets",
        sourceDir = "wbnovel",
    ),Extension(
        name = "WuxiaWorld",
        versionCode = 1,
        libVersion = "1",
        lang = "en",
        description = "",
        nsfw = false,
        icon = DEFAULT_ICON,
        assetsDir = "multisrc/madara/wuxiaworld/assets",
        sourceDir = "wuxiaworld",
    ),
    Extension(
        name = "MysticalSeries",
        versionCode = 1,
        libVersion = "1",
        lang = "en",
        description = "",
        nsfw = false,
        icon = DEFAULT_ICON,
        assetsDir = "multisrc/madara/mysticalseries/assets",
        sourceDir = "mysticalseries",
    ),
    Extension(
        name = "MoreNovel",
        versionCode = 1,
        libVersion = "1",
        lang = "in",
        description = "",
        nsfw = false,
        icon = DEFAULT_ICON,
        assetsDir = "multisrc/madara/morenovel/assets",
        sourceDir = "morenovel",
    ),
    Extension(
        name = "Novel4Up",
        versionCode = 1,
        libVersion = "1",
        lang = "ar",
        description = "",
        nsfw = false,
        icon = DEFAULT_ICON,
        assetsDir = "multisrc/madara/novel4up/assets",
        sourceDir = "novel4up",
    ),
    Extension(
        name = "TeamXNovel",
        versionCode = 1,
        libVersion = "1",
        lang = "ar",
        description = "",
        nsfw = false,
        icon = DEFAULT_ICON,
        assetsDir = "multisrc/madara/teamxnovel/assets",
        sourceDir = "teamxnovel",
    ),
    Extension(
        name = "TurkceLightNovels",
        versionCode = 1,
        libVersion = "1",
        lang = "tu",
        description = "",
        nsfw = false,
        icon = DEFAULT_ICON,
        assetsDir = "multisrc/madara/turkcelightnovels/assets",
        sourceDir = "turkcelightnovels",
    ),
    Extension(
        name = "SonicMTL",
        versionCode = 1,
        libVersion = "1",
        lang = "en",
        description = "",
        nsfw = false,
        icon = DEFAULT_ICON,
        assetsDir = "multisrc/madara/sonicmtl/assets",
        sourceDir = "sonicmtl",
    ),
    Extension(
        name = "SleepyTranslations",
        versionCode = 1,
        libVersion = "1",
        lang = "en",
        description = "",
        nsfw = false,
        icon = DEFAULT_ICON,
        assetsDir = "multisrc/madara/sleepytranslations/assets",
        sourceDir = "sleepytranslations",
    ),
    Extension(
        name = "MTLNovelClub",
        versionCode = 1,
        libVersion = "1",
        lang = "en",
        description = "",
        nsfw = false,
        icon = DEFAULT_ICON,
        assetsDir = "multisrc/madara/mtlnovelclub/assets",
        sourceDir = "mtlnovelclub",
    ),
    Extension(
        name = "Novelstic",
        versionCode = 1,
        libVersion = "1",
        lang = "en",
        description = "",
        nsfw = false,
        icon = DEFAULT_ICON,
        assetsDir = "multisrc/madara/novelstic/assets",
        sourceDir = "novelstic",
    ),





    ).also(::register)