listOf(
    Extension(
        name = "Neosekaitranslations",
        versionCode = 2,
        libVersion = "2",
        lang = "en",
        description = "",
        nsfw = false,
        icon = DEFAULT_ICON,
        assetsDir = "multisrc/madara/neosekaitranslations/assets",
        sourceDir = "neosekaitranslations",
    ),
    Extension(
        name = "Armtl",
        versionCode = 2,
        libVersion = "2",
        lang = "ar",
        description = "",
        nsfw = false,
        icon = DEFAULT_ICON,
        assetsDir = "multisrc/madara/armtl/assets",
        sourceDir = "armtl",
    ),
    Extension(
        name = "HizoManga",
        versionCode = 3,
        libVersion = "2",
        lang = "ar",
        description = "",
        nsfw = false,
        icon = DEFAULT_ICON,
        assetsDir = "multisrc/madara/armtl/assets",
        sourceDir = "hizomanga",
    ),
    Extension(
        name = "Zinnovel",
        versionCode = 2,
        libVersion = "2",
        lang = "en",
        description = "",
        nsfw = false,
        icon = DEFAULT_ICON,
        assetsDir = "multisrc/madara/zinnovel/assets",
        sourceDir = "zinnovel",
    ),
    Extension(
        name = "NovelTranslate",
        versionCode = 2,
        libVersion = "2",
        lang = "en",
        description = "",
        nsfw = false,
        icon = DEFAULT_ICON,
        assetsDir = "multisrc/madara/noveltranslate/assets",
        sourceDir = "noveltranslate",
    ),
    Extension(
        name = "LunarLetters",
        versionCode = 2,
        libVersion = "2",
        lang = "en",
        description = "",
        nsfw = false,
        icon = DEFAULT_ICON,
        assetsDir = "multisrc/madara/lunarletters/assets",
        sourceDir = "lunarletters",
    ),
    Extension(
        name = "SleepyTranslations",
        versionCode = 2,
        libVersion = "2",
        lang = "en",
        description = "",
        nsfw = false,
        icon = DEFAULT_ICON,
        assetsDir = "multisrc/madara/sleepytranslations/assets",
        sourceDir = "sleepytranslations",
    ),
    Extension(
        name = "Freenovel",
        versionCode = 2,
        libVersion = "2",
        lang = "en",
        description = "",
        nsfw = false,
        icon = DEFAULT_ICON,
        assetsDir = "multisrc/madara/freenovel/assets",
        sourceDir = "freenovel",
    ),
    Extension(
        name = "FirstKissNovel",
        versionCode = 2,
        libVersion = "2",
        lang = "en",
        description = "",
        nsfw = false,
        icon = DEFAULT_ICON,
        assetsDir = "multisrc/madara/firstkissnovel/assets",
        sourceDir = "firstkissnovel",
    ),
    Extension(
        name = "NovelMultiverse",
        versionCode = 2,
        libVersion = "2",
        lang = "en",
        description = "",
        nsfw = false,
        icon = DEFAULT_ICON,
        assetsDir = "multisrc/madara/novelmultiverse/assets",
        sourceDir = "novelmultiverse",
    ),
    Extension(
        name = "LightNovelHeaven",
        versionCode = 2,
        libVersion = "2",
        lang = "en",
        description = "",
        nsfw = false,
        icon = DEFAULT_ICON,
        assetsDir = "multisrc/madara/lightnovelheaven/assets",
        sourceDir = "lightnovelheaven",
    ),
    Extension(
        name = "ArNovel",
        versionCode = 4,
        libVersion = "2",
        lang = "ar",
        description = "",
        nsfw = false,
        icon = DEFAULT_ICON,
        assetsDir = "multisrc/madara/arnovel/assets",
        sourceDir = "arnovel",
    ),
    Extension(
        name = "MeioNovel",
        versionCode = 2,
        libVersion = "1",
        lang = "in",
        description = "",
        nsfw = false,
        icon = DEFAULT_ICON,
        assetsDir = "multisrc/madara/meionovel/assets",
        sourceDir = "meionovel",
    ),
    Extension(
        name = "WebNovelLover",
        versionCode = 2,
        libVersion = "1",
        lang = "en",
        description = "",
        nsfw = false,
        icon = DEFAULT_ICON,
        assetsDir = "multisrc/madara/webnovelover/assets",
        sourceDir = "webnovelover",
    ),
    Extension(
        name = "CrateNovel",
        versionCode = 2,
        libVersion = "1",
        lang = "en",
        description = "",
        nsfw = false,
        icon = DEFAULT_ICON,
        assetsDir = "multisrc/madara/cratenovel/assets",
        sourceDir = "cratenovel",
    ),
    Extension(
        name = "ClickNovel",
        versionCode = 2,
        libVersion = "1",
        lang = "en",
        description = "",
        nsfw = false,
        icon = DEFAULT_ICON,
        assetsDir = "multisrc/madara/clicknovel/assets",
        sourceDir = "clicknovel",
    ),
    Extension(
        name = "ReadWebNovels",
        versionCode = 2,
        libVersion = "1",
        lang = "en",
        description = "",
        nsfw = false,
        icon = DEFAULT_ICON,
        assetsDir = "multisrc/madara/readwebnovels/assets",
        sourceDir = "readwebnovels",
    ),
    Extension(
        name = "MysticalSeries",
        versionCode = 2,
        libVersion = "1",
        lang = "en",
        description = "",
        nsfw = false,
        icon = DEFAULT_ICON,
        assetsDir = "multisrc/madara/mysticalseries/assets",
        sourceDir = "mysticalseries",
    ),
    Extension(
        name = "MoreNovel",
        versionCode = 2,
        libVersion = "1",
        lang = "in",
        description = "",
        nsfw = false,
        icon = DEFAULT_ICON,
        assetsDir = "multisrc/madara/morenovel/assets",
        sourceDir = "morenovel",
    ),
    Extension(
        name = "Novel4Up",
        versionCode = 2,
        libVersion = "1",
        lang = "ar",
        description = "",
        nsfw = false,
        icon = DEFAULT_ICON,
        assetsDir = "multisrc/madara/novel4up/assets",
        sourceDir = "novel4up",
    ),
    Extension(
        name = "TurkceLightNovels",
        versionCode = 2,
        libVersion = "1",
        lang = "tu",
        description = "",
        nsfw = false,
        icon = DEFAULT_ICON,
        assetsDir = "multisrc/madara/turkcelightnovels/assets",
        sourceDir = "turkcelightnovels",
    ),
    Extension(
        name = "SonicMTL",
        versionCode = 2,
        libVersion = "1",
        lang = "en",
        description = "",
        nsfw = false,
        icon = DEFAULT_ICON,
        assetsDir = "multisrc/madara/sonicmtl/assets",
        sourceDir = "sonicmtl",
    ),
    Extension(
        name = "MTLNovelClub",
        versionCode = 2,
        libVersion = "1",
        lang = "en",
        description = "",
        nsfw = false,
        icon = DEFAULT_ICON,
        assetsDir = "multisrc/madara/mtlnovelclub/assets",
        sourceDir = "mtlnovelclub",
    ),
Extension(
        name = "Azora",
        versionCode = 3,
        libVersion = "1",
        lang = "ar",
        description = "",
        nsfw = false,
        icon = DEFAULT_ICON,
        assetsDir = "multisrc/madara/azora/assets",
        sourceDir = "azora",
    ),
    // ═══════════════════════════════════════════════════════════════
    // New sources migrated from lightnovel-crawler
    // ═══════════════════════════════════════════════════════════════
    Extension(
        name = "AquaManga",
        versionCode = 1,
        libVersion = "2",
        lang = "en",
        description = "",
        nsfw = false,
        icon = DEFAULT_ICON,
        sourceDir = "aquamanga",
    ),
    Extension(
        name = "Beautymanga",
        versionCode = 1,
        libVersion = "2",
        lang = "en",
        description = "",
        nsfw = false,
        icon = DEFAULT_ICON,
        sourceDir = "beautymanga",
    ),
    Extension(
        name = "BonNovel",
        versionCode = 1,
        libVersion = "2",
        lang = "en",
        description = "",
        nsfw = false,
        icon = DEFAULT_ICON,
        sourceDir = "bonnovel",
    ),
    Extension(
        name = "BoxNovel",
        versionCode = 1,
        libVersion = "2",
        lang = "en",
        description = "",
        nsfw = false,
        icon = DEFAULT_ICON,
        sourceDir = "boxnovel",
    ),
    Extension(
        name = "CoffeeManga",
        versionCode = 1,
        libVersion = "2",
        lang = "en",
        description = "",
        nsfw = false,
        icon = DEFAULT_ICON,
        sourceDir = "coffeemanga",
    ),
    Extension(
        name = "FantasyWorldOnline",
        versionCode = 1,
        libVersion = "2",
        lang = "en",
        description = "",
        nsfw = false,
        icon = DEFAULT_ICON,
        sourceDir = "fantasyworldonline",
    ),
    Extension(
        name = "FenrirTranslations",
        versionCode = 1,
        libVersion = "2",
        lang = "en",
        description = "",
        nsfw = false,
        icon = DEFAULT_ICON,
        sourceDir = "fenrirtranslations",
    ),
    Extension(
        name = "FreeFullNovel",
        versionCode = 1,
        libVersion = "2",
        lang = "en",
        description = "",
        nsfw = false,
        icon = DEFAULT_ICON,
        sourceDir = "freefullnovel",
    ),
    Extension(
        name = "FreeManga",
        versionCode = 1,
        libVersion = "2",
        lang = "en",
        description = "",
        nsfw = false,
        icon = DEFAULT_ICON,
        sourceDir = "freemanga",
    ),
    Extension(
        name = "HariManga",
        versionCode = 1,
        libVersion = "2",
        lang = "en",
        description = "",
        nsfw = false,
        icon = DEFAULT_ICON,
        sourceDir = "harimanga",
    ),
    Extension(
        name = "IsekaiScan",
        versionCode = 1,
        libVersion = "2",
        lang = "en",
        description = "",
        nsfw = false,
        icon = DEFAULT_ICON,
        sourceDir = "isekaiscan",
    ),
    Extension(
        name = "IsekaiScanEU",
        versionCode = 1,
        libVersion = "2",
        lang = "en",
        description = "",
        nsfw = false,
        icon = DEFAULT_ICON,
        sourceDir = "isekaiscaneu",
    ),
    Extension(
        name = "KingManga",
        versionCode = 1,
        libVersion = "2",
        lang = "en",
        description = "",
        nsfw = false,
        icon = DEFAULT_ICON,
        sourceDir = "kingmanga",
    ),
    Extension(
        name = "KissManga",
        versionCode = 1,
        libVersion = "2",
        lang = "en",
        description = "",
        nsfw = false,
        icon = DEFAULT_ICON,
        sourceDir = "kissmanga",
    ),
    Extension(
        name = "MangaRead",
        versionCode = 1,
        libVersion = "2",
        lang = "en",
        description = "",
        nsfw = false,
        icon = DEFAULT_ICON,
        sourceDir = "mangaread",
    ),
    Extension(
        name = "MangaRockTeam",
        versionCode = 1,
        libVersion = "2",
        lang = "en",
        description = "",
        nsfw = false,
        icon = DEFAULT_ICON,
        sourceDir = "mangarockteam",
    ),
    Extension(
        name = "MangaRosie",
        versionCode = 1,
        libVersion = "2",
        lang = "en",
        description = "",
        nsfw = false,
        icon = DEFAULT_ICON,
        sourceDir = "mangarosie",
    ),
    Extension(
        name = "MangaTX",
        versionCode = 1,
        libVersion = "2",
        lang = "en",
        description = "",
        nsfw = false,
        icon = DEFAULT_ICON,
        sourceDir = "mangatx",
    ),
    Extension(
        name = "MangaWeebs",
        versionCode = 1,
        libVersion = "2",
        lang = "en",
        description = "",
        nsfw = false,
        icon = DEFAULT_ICON,
        sourceDir = "mangaweebs",
    ),
    Extension(
        name = "ManhwachillLove",
        versionCode = 1,
        libVersion = "2",
        lang = "en",
        description = "",
        nsfw = false,
        icon = DEFAULT_ICON,
        sourceDir = "manhwachilllove",
    ),
    Extension(
        name = "MixedNovelNet",
        versionCode = 1,
        libVersion = "2",
        lang = "en",
        description = "",
        nsfw = false,
        icon = DEFAULT_ICON,
        sourceDir = "mixednovelnet",
    ),
    Extension(
        name = "MyBoxNovel",
        versionCode = 1,
        libVersion = "2",
        lang = "en",
        description = "",
        nsfw = false,
        icon = DEFAULT_ICON,
        sourceDir = "myboxnovel",
    ),
    Extension(
        name = "NewNovelOrg",
        versionCode = 1,
        libVersion = "2",
        lang = "en",
        description = "",
        nsfw = false,
        icon = DEFAULT_ICON,
        sourceDir = "newnovelorg",
    ),
    Extension(
        name = "NoobChan",
        versionCode = 1,
        libVersion = "2",
        lang = "en",
        description = "",
        nsfw = false,
        icon = DEFAULT_ICON,
        sourceDir = "noobchan",
    ),
    Extension(
        name = "OneKissNovel",
        versionCode = 1,
        libVersion = "2",
        lang = "en",
        description = "",
        nsfw = false,
        icon = DEFAULT_ICON,
        sourceDir = "onekissnovel",
    ),
    Extension(
        name = "PianManga",
        versionCode = 1,
        libVersion = "2",
        lang = "en",
        description = "",
        nsfw = false,
        icon = DEFAULT_ICON,
        sourceDir = "pianmanga",
    ),
    Extension(
        name = "RandomNovel",
        versionCode = 1,
        libVersion = "2",
        lang = "en",
        description = "",
        nsfw = false,
        icon = DEFAULT_ICON,
        sourceDir = "randomnovel",
    ),
    Extension(
        name = "Readmtl",
        versionCode = 1,
        libVersion = "2",
        lang = "en",
        description = "",
        nsfw = false,
        icon = DEFAULT_ICON,
        sourceDir = "readmtl",
    ),
    Extension(
        name = "Toonily",
        versionCode = 1,
        libVersion = "2",
        lang = "en",
        description = "",
        nsfw = false,
        icon = DEFAULT_ICON,
        sourceDir = "toonily",
    ),
    Extension(
        name = "UsefulNovel",
        versionCode = 1,
        libVersion = "2",
        lang = "en",
        description = "",
        nsfw = false,
        icon = DEFAULT_ICON,
        sourceDir = "usefulnovel",
    ),
    Extension(
        name = "ZetroTranslation",
        versionCode = 1,
        libVersion = "2",
        lang = "en",
        description = "",
        nsfw = false,
        icon = DEFAULT_ICON,
        sourceDir = "zetrotranslation",
    ),
    Extension(
        name = "ZinManga",
        versionCode = 1,
        libVersion = "2",
        lang = "en",
        description = "",
        nsfw = false,
        icon = DEFAULT_ICON,
        sourceDir = "zinmanga",
    ),
    Extension(
        name = "Lnmtlfr",
        versionCode = 1,
        libVersion = "2",
        lang = "fr",
        description = "",
        nsfw = false,
        icon = DEFAULT_ICON,
        sourceDir = "lnmtlfr",
    ),
    Extension(
        name = "MassNovel",
        versionCode = 1,
        libVersion = "2",
        lang = "fr",
        description = "",
        nsfw = false,
        icon = DEFAULT_ICON,
        sourceDir = "massnovel",
    ),
    Extension(
        name = "Foxaholic",
        versionCode = 1,
        libVersion = "2",
        lang = "multi",
        description = "",
        nsfw = false,
        icon = DEFAULT_ICON,
        sourceDir = "foxaholic",
    ),
    Extension(
        name = "BestManga",
        versionCode = 1,
        libVersion = "2",
        lang = "ru",
        description = "",
        nsfw = false,
        icon = DEFAULT_ICON,
        sourceDir = "bestmanga",
    ),
).also(::register)
