listOf(
    Extension(
        name = "ReadNovelFull",
        versionCode = 1,
        libVersion = "2",
        lang = "en",
        description = "Read novels online free",
        nsfw = false,
        icon = DEFAULT_ICON,
        assetsDir = "multisrc/readnovelfull/readnovelfull/assets",
        sourceDir = "readnovelfull",
    ),
    Extension(
        name = "AllNovel",
        versionCode = 1,
        libVersion = "2",
        lang = "en",
        description = "Read novels online",
        nsfw = false,
        icon = DEFAULT_ICON,
        assetsDir = "multisrc/readnovelfull/allnovel/assets",
        sourceDir = "allnovel",
    ),
    Extension(
        name = "NovelFull",
        versionCode = 1,
        libVersion = "2",
        lang = "en",
        description = "Read novels online",
        nsfw = false,
        icon = DEFAULT_ICON,
        assetsDir = "multisrc/readnovelfull/novelfull/assets",
        sourceDir = "novelfull",
    ),
    Extension(
        name = "LibRead",
        versionCode = 1,
        libVersion = "2",
        lang = "en",
        description = "Read novels online",
        nsfw = false,
        icon = DEFAULT_ICON,
        assetsDir = "multisrc/readnovelfull/libread/assets",
        sourceDir = "libread",
    ),
    Extension(
        name = "NovelBin",
        versionCode = 1,
        libVersion = "2",
        lang = "en",
        description = "Read novels online",
        nsfw = false,
        icon = DEFAULT_ICON,
        assetsDir = "multisrc/readnovelfull/novelbin/assets",
        sourceDir = "novelbin",
    ),
    Extension(
        name = "AllNovelFull",
        versionCode = 1,
        libVersion = "2",
        lang = "en",
        description = "Read novels online",
        nsfw = false,
        icon = DEFAULT_ICON,
        assetsDir = "multisrc/readnovelfull/allnovelfull/assets",
        sourceDir = "allnovelfull",
    ),
    Extension(
        name = "BoxNovel",
        versionCode = 1,
        libVersion = "2",
        lang = "en",
        description = "Read novels online",
        nsfw = false,
        icon = DEFAULT_ICON,
        assetsDir = "multisrc/readnovelfull/boxnovel/assets",
        sourceDir = "boxnovel",
    ),
).also(::register)
